### ISSUE TITLE
フォロー機能の復活

### ISSUE THREAD

**Issue by oinarisummer** [concrnt/concrnt-world#382]
## What - 提供したい体験
リストに関わらず追いたいようなユーザーを設定する機能としてのフォロー

## Why (Optional)
途中の更新でユーザーのフォローは各リストへの追加に機能が変更された
現行だと全部のリストを選択したり、リストを増やしたときに一人ずつ追加しに行かなければならないのが面倒

あとついでに#380とか、#368でボタンが二重になってる状態も一挙に解決できそう

**Comment by totegamma** [comment]
復活🎉
