### ISSUE TITLE
インポートの入力欄において、自動入力を可能にする

### ISSUE THREAD

**Issue by fono09** [concrnt/concrnt-world#404]
## Problem / 問題点
インポート( `/import` )の入力欄(シークレットコード,秘密鍵共用)で、各種パスワード管理ツールが動作しない。

## Solution (Optional)
インポートの入力欄が現状input[type=text]になっている箇所を、input[type=password]としたところ、少なくとも1Passwordで自動入力が可能になった。パスワード表示を入力欄内から外せば、表示とも両立できる、あるいはシークレットコードや秘密鍵の表示を諦める。

https://github.com/totegamma/concurrent-world/assets/6201749/7d4ca70a-2132-41f0-ad2a-febc8b105edc

**Comment by totegamma** [comment]
デフォルトでtype=passwordにして、よくあるお目目アイコンで切り替えられるようなUIにしようかな〜と思います！
