### ISSUE TITLE
カーソル位置に絵文字のショートコードが入力されるようにする。

### ISSUE THREAD

**Issue by ouroboros723** [concrnt/concrnt-world#415]
## Problem / 問題点
<What / Where / Why>
Draftの絵文字入力時、カーソルの位置にかかわらず文頭に必ず挿入される。
![concurrent_emoji_cursor](https://github.com/totegamma/concurrent-world/assets/23020033/60d0ff68-f620-4bdf-9d5a-02e1ece80e4b)

文章を書いている途中で文字入力と同じ感覚で入力したいため、必ず文頭に挿入される仕様だとストレスを感じるかもしれない。
なお、各SNSサイトでは絵文字パレットから入力された際、カーソル位置に入力されるのが一般的な挙動になっている。

- Misskey
![concurrent_emoji_cursor2](https://github.com/totegamma/concurrent-world/assets/23020033/4dd273ec-863e-46b2-89be-a9bd8f44f509)

- X(Twitter)
![concurrent_emoji_cursor3](https://github.com/totegamma/concurrent-world/assets/23020033/5a454c3f-fbc2-400b-a575-9a88574a8e93)

## Solution (Optional)
<How>
Javascriptにはカーソル位置を取得するAPIがあるため、これを利用すれば実現できそうである。

[JavaScript でテキストエリア内のカーソルのある位置に文字列を挿入する方法 - Qiita](https://qiita.com/noraworld/items/d6334a4f9b07792200a5)

**Comment by totegamma** [comment]
今そもそも 文中で `:` を入力したときはその位置に絵文字が挿入されるようになっているのでそこの処理といい感じに統合したらいい感じになりそう！

**Comment by totegamma** [comment]
https://github.com/totegamma/concurrent-world/pull/459/commits/a278d957e62fc260bb32a7df5b396844f667d190 で修正
