### ISSUE TITLE
絵文字ピッカーで下二段が選択できない

### ISSUE THREAD

**Issue by 7ka-Hiira** [concrnt/concrnt-world#475]
## Expected Behaviour / 期待した挙動
すべての絵文字が選択できる

## Actual Behavior / 実際の挙動
長い絵文字パックを下にスクロールしていくと、下二段が表示されない

## Steps to Reproduce / 再現方法
ピッカーで長い絵文字パック(Twemojiなど)のタブを表示し、一番下までスクロールする

## Additional Information / 追加情報
スクリーンショットやリクエストのTraceIDなど
https://github.com/totegamma/concurrent-world/blob/develop/src/context/EmojiPickerContext.tsx#L292
ここ200pxな気がしています

**Comment by totegamma** [comment]
気づいてなかった！！！！
Co-authorで修正入れさせていただきました！レポートありがとうございます！！！！
