### ISSUE TITLE
リンクプレビューの表示を投稿前に確認可能にし表示するかどうかは投稿者の意思に委ねたい

### ISSUE THREAD

**Issue by waonme** [concrnt/concrnt-world#493]
## Problem / 問題点
投稿するまでどんな情報が表示されるかがわからない
足りない情報があれば手入力で文字や追加のメディアを添付したくなることがある
リンクプレビューの内容は不要な情報しかない場合がある

## Solution (Optional)
投稿前にリンクプレビューの内容を確認可能にし、任意でリンクプレビューをオフにできるように。
（あるいはBluesky公式のように意思を持ってオンにする実装の方がいいかもしれない？）
URLごとに制御可能なように。

**Comment by totegamma** [comment]
related: #494

**Comment by totegamma** [comment]
これconcrnt.world以外のクライアントでは表示されますみたいなのがありうると思っていて、
とはいえじゃぁどんな人もそれを表示しちゃいけませんって強制するのも違うなと。

そもそも張ったリンクがogp広告してる以上仕方がないので、

1. 自衛という意味でも編集時に表示してogpが見えうるということを通知する
2. cwの中に入れていれば**デフォルトでは**表示されないようにする

辺りが落としどころかなと

**Comment by totegamma** [comment]
一旦これで
- 投稿時のプレビューは実装 ( #735 )
- またCWで隠せるように( #641 )
- urlプレビューの表示はある意味閲覧者にとっての自衛でもあるので、完全なるOFFは投稿者側ではやらない
