### ISSUE TITLE
無効化したサブキーを非表示にする

### ISSUE THREAD

**Issue by ryotn** [concrnt/concrnt-world#506]
## Problem / 問題点
<What / Where / Why>
無効化したサブキーが残ったままなので表示だけでも消したい（内部的には無理っぽい）

## Solution (Optional)
<How>
無効化したら表示上だけ消える！

**Comment by totegamma** [comment]
これなのですが、今後サブキーの表示自体を親子関係がよくわかるようにツリー状に表示したいと思ってて、今パッチいただいてもその変更でまた再設計になる可能性が高いです...
それはそれとして、ツリー表示は現在優先度低めで変更が入るとしてもまだ先になりそうなので、パパっとできちゃうからとりあえずこれで～という感じでよければ大歓迎です！

**Comment by ryotn** [comment]
あ～～～了解です！
非表示だけなら一行ちょっといじるだけで行けそうなんでパパっとやっちゃいますね～！

**Comment by totegamma** [comment]
PRありがとうございます！！
余力があればなんですが、最初から完全に非表示にするとユーザーが「消せるんだ！」と勘違いしてしまうかもなので、「最初は全部表示しておいて、スイッチか何かで隠せるオプションをその場に提示する」っていうのはどうでしょうか...!

https://mui.com/material-ui/react-switch/

**Comment by ryotn** [comment]
後でやってみます！！

**Comment by ryotn** [comment]
Switchで表示/非表示できるようにしてみました。
こんな感じでどうでしょうか・・・？

<video src="https://github.com/totegamma/concurrent-world/assets/13426723/52e55264-e4a0-41a6-af8b-7e0500116894"></video>

**Comment by totegamma** [comment]
ツリー表示になて非表示にできなくなったので再度問題に...
