### ISSUE TITLE
マスターキーからサブキーに切り替えたユーザーは、"サブキーでのログイン"を活用してもらえない可能性がある。

### ISSUE THREAD

**Issue by ouroboros723** [concrnt/concrnt-world#527]
### What・Where
マスターキーからサブキーへの切り替え時

### Why
ログイン時の選択肢として"サブキーでログイン"があります。
![image](https://github.com/totegamma/concurrent-world/assets/23020033/e52b5554-da32-4e8a-a838-723bcf2f3f16)

しかし、マスターキーからサブキーに切り替えた際、ユーザーに生成されたサブキーが提示されません。

<現在( dceb4fa662a7e6b64c34caa8b00cb9eae61e5a16 )のフロー>
![image](https://github.com/totegamma/concurrent-world/assets/23020033/a54201bd-c42b-42b5-ab04-7a248adc09e7)
↓
![image](https://github.com/totegamma/concurrent-world/assets/23020033/e3e1cda7-bd61-4f41-bc8b-18ac49c27f87)

この場合、せっかくサブキーでのログイン機能があるのに、ユーザーはマスターキーを使用する機会しかなくなり、サブキーでログインする機能が生かされない可能性があります。

### How
下記の2つの案があります。

1.  サブキー切り替え時に1度だけ画面上にサブキーを表示する
ユーザーに生成したサブキーを保存する機会を与えます。

2. サブキーは1ログインにつき必ず1つ発行するもの、使いまわさないもの、とし、サブキーでのログインを廃止する。
イメージとしてはGitHubの個人用アクセス トークンです。

以上、ご確認の程何卒よろしくお願い致します。

**Comment by totegamma** [comment]
起票ありがとうございます！
こちらなんですが、今のところとしては切り替え時に色々情報を見せるとユーザー的に大変かなということであえて表示してないです！
代わりにログインQRの画面で一応確認できるようにはなっているのですが、正直ここは分かりくいなーとは思っており... いい感じにしたいですよね！

![image](https://github.com/totegamma/concurrent-world/assets/7270849/e70ab68c-61d1-45e3-917c-1ae54a023f11)


実際ユーザーがQR以外でのログインを行うユースケースがあんまり調べきれてないのでそこ次第かな...とは思っています。

**Comment by ouroboros723** [comment]
返信ありがとうございます！
なるほどですね👀

ユースケースとして想定できるのは

- 初回ログイン
- PCなどでカメラが搭載されていない端末からのログイン

でしょうか...？（マスターキーで賄える内容ではありますが...）

取り敢えずQRコード以外のログインが実際どれだけ使用されてるかの統計を取るコードを導入する、というのもありえそうですね🤔

**Comment by totegamma** [comment]
いろいろ悩む点はありますが、
- 各所にサブキーをコピーするボタンを配置
- チュートリアルでの案内
を行ったので一旦Close
