### ISSUE TITLE
探索ページでユーザーIDをコピーできない

### ISSUE THREAD

**Issue by schwarzewald** [concrnt/concrnt-world#529]
探索ページで他のユーザーの一覧が表示されるページでそのユーザーの名前の横に出ているクリップボードマークからユーザーIDをコピーしようとしてもクリップボードに何もコピーされません。
また、ユーザー名などを押してもユーザーのページに行けないのですが不具合でしょうか？
Mac OS 14.4.1のSafariとFirefoxから試してみましたがどちらも同じでした。

**Comment by totegamma** [comment]
起票ありがとうございます！！ここ確実に作られてないですね。修正対象になります🙏

**Comment by totegamma** [comment]
こちら修正しました！

**Comment by schwarzewald** [comment]
ありがとうございます！ユーザーページへの移動とユーザーIDのコピー出来るようになってました！
