### ISSUE TITLE
新しいリストのExploreボタンからストリーム検索画面へ遷移しようとすると停止する

### ISSUE THREAD

**Issue by ouroboros723** [concrnt/concrnt-world#530]
## Expected Behaviour / 期待した挙動
新しいリストのExploreボタンをクリックすると、ストリーム検索画面へ遷移する。
![nBa0EaI](https://github.com/totegamma/concurrent-world/assets/23020033/65623436-c2e1-4db1-b4de-a8d3c1472f57)
↓
![image](https://github.com/totegamma/concurrent-world/assets/23020033/313a038b-f449-4734-b999-a5b82e2144c7)

## Actual Behavior / 実際の挙動
新しいリストのExploreボタンをクリックすると、ブランクな画面が表示されてしまう。
![nBa0EaI](https://github.com/totegamma/concurrent-world/assets/23020033/65623436-c2e1-4db1-b4de-a8d3c1472f57)
↓
![Xp22UOC](https://github.com/totegamma/concurrent-world/assets/23020033/f878af34-8ef7-46b7-af7a-6dc520b2757b)

## Steps to Reproduce / 再現方法
1. サイドバーから新しいリストを作成
2. リスト一覧から新しく作成したリストをクリック
3. 表示されたリストページ内の"GO EXPLORE"ボタンをクリックする

**Comment by totegamma** [comment]
これ、リンクが古くて現在は/explorerになっている
https://github.com/totegamma/concurrent-world/blob/develop/src/pages/ListPage.tsx#L197

が、本当は/:tabも期待されている(ここでは/explorer/streamsかな)やつですね
https://github.com/totegamma/concurrent-world/blob/develop/src/App.tsx#L339
