### ISSUE TITLE
movファイルがChromeで再生できない

### ISSUE THREAD

**Issue by ryotn** [concrnt/concrnt-world#603]
## Problem / 問題点
iPhoneなどのAppleデバイスで撮影された動画をアップロードすると、Chromeを使っている環境では再生できなくなってしまう。

## Solution (Optional)
videoタグの `type` が `video/quicktime` だとChromeで再生ができないが、 `video/mp4` だと再生できるので `video/mp4` にする（固定していいのかは不明？）

この辺いじればどうにかなる？
https://github.com/totegamma/concurrent-world/blob/develop/src/components/Draft.tsx#L186

**Comment by totegamma** [comment]
ありがとうございます！
選択肢としては以下の3つでしょうか...
1. video/quicktimeが渡されたときだけvideo/mp4に強制的に置き換えちゃう
2. sourceの2番目にtype指定なしのsourceを追加する
3. そもそもtype指定しない

なんなら3のそもそもtype指定撤去しちゃっても良くないかと思っているところでもあるんですが、これなんで必要なんだっけな......

**Comment by ryotn** [comment]
言われてみれば`type`無くても再生できますね・・・
とりあえずChrome、Safari、Firefoxで再生できるのは確認出来たんで`type`撤去のPR後で出します。

**Comment by ryotn** [comment]
PR マージ済み
https://github.com/totegamma/concurrent-world/pull/605
