### ISSUE TITLE
Safariで動画のサムネイルが表示されない

### ISSUE THREAD

**Issue by ryotn** [concrnt/concrnt-world#604]
## Problem / 問題点
Safariで動画のサムネイルが表示されていない

## Solution (Optional)
動画URL末尾に`#t=0.1`を入れると表示される
（他のブラウザで問題ないかは未確認）
https://qiita.com/mtoutside/items/3210f24232345d75829d

**Comment by totegamma** [comment]
よさそうよさそうよさそう
