### ISSUE TITLE
絵文字を更新すると過去の投稿まで新しいもので表示されてしまう

### ISSUE THREAD

**Issue by waonme** [concrnt/concrnt-world#625]
## Problem / 問題点
<What / Where / Why>
思い出は当時のままで振り返りたい
意味が変わってしまったり内容が成立しなくなってしまったりすることがある

**Comment by waonme** [comment]
そもそも絵文字って更新時にはファイル名を変えておいた方がいいのか？
絵文字パックや絵文字画像ファイルの管理はどうあるべきなんだろう

**Comment by totegamma** [comment]
ご指摘のとおり、絵文字パックを更新する人が画像差し替えではなくてそのshortcodeに対応する画像URLを差し替えるのがベストっぽい。(キャッシュの観点からもこっちの方が好ましい)

コンカレ側で対応できることがあるとすれば都度画像データをコピーして投稿に埋め込んでしまうことだけど、おもにコピーライトの観点から微妙かも
