### ISSUE TITLE
CWの開閉ステータスによってurl summaryの表示非表示を切り替えたい

### ISSUE THREAD

**Issue by waonme** [concrnt/concrnt-world#641]
## Problem / 問題点
<What / Where / Why>
閲覧に注意が必要なサイトのURLを入れたところ内容が初めから表示されてしまった

**Comment by totegamma** [comment]
innertextからリンクを抽出するのが実装として簡単そう
ただ、開閉等の変更イベントをグローバルに取得する方法が必要

**Comment by totegamma** [comment]
mutation observerを使うのはちょっと大袈裟かも？ summaryproviderみたいなcontextを用意して、ontoggleでupdateを呼ぶのが良さそう
