### ISSUE TITLE
ChromeとFireFoxで動画のアップロードができない

### ISSUE THREAD

**Issue by ryotn** [concrnt/concrnt-world#732]
## Expected Behaviour / 期待した挙動
動画のアップロードが出来る

## Actual Behavior / 実際の挙動
動画のアップロードができない

## Steps to Reproduce / 再現方法
- ストレージプロバイダはS3に設定（R2かMinIOしか試せてない）
- ChromeかFireFoxで動画をアップロードする
- 「Uploading...」のまま止まってしまう

## Additional Information / 追加情報
<video src="https://github.com/user-attachments/assets/b20f2ed2-bd4b-48d8-866e-5bb2c06caad3" >
</video>

- Safari/Mobile Safariではアップロードできる
- バケットにはアップロードされている
- 画像はアップロードできる

ブラウザのDevToolsで見るとエラーが出てる？
![スクリーン ショット 2024-12-09 に 10 49 35 午前](https://github.com/user-attachments/assets/6afca8c4-a7ff-49e4-b6e1-c0a5c7792fc1)

## その他
ストレージプロバイダをimgurやDomainにすると「Failed to upload image」と出る
（imgurやDomainは動画は非対応だっけ？）

![z](https://github.com/user-attachments/assets/1d956aa0-d555-4618-b220-5a7b0d274e69)

**Comment by totegamma** [comment]
1点だけ気になっているんですが、これFailed to uploadになるのは数秒後とかですか？それとも添付した瞬間？

あと今日明日でアップロードの進捗を表示できるようにfetchからXMLHttpRequestに変更しようと思ってます...! (

**Comment by totegamma** [comment]
ごめんなさい動画添付してくれてるのにちゃんと見れてなかった(この動画の後にFailed to uploadが出るのかな？)

**Comment by ryotn** [comment]
「Failed to upload image」が出てくるのはストレージプロバイダがimgurやDomainの時のみで、動画選択後すぐに出てきます。
S3だと「Failed to upload image」すら出てきません・・・😭

**Comment by totegamma** [comment]
なるほど 🤔 
一旦XMLHttpRequestリプレイスしてみて再度確認かな......

**Comment by totegamma** [comment]
#734 で治ったかも？

**Comment by ryotn** [comment]
修正ありがとうございます！
治ってるの確認できたのでCloseします！
