### ISSUE TITLE
Twitterで言うWeb Intentのようなものが欲しい

### ISSUE THREAD

**Issue by ryotn** [concrnt/concrnt-world#757]
## What - 提供したい体験
Webサイトにコンカレへの共有ボタンを設置したい！そのためにはWeb Intentが必要。。。
iOSのショートカットやAndroidのTaskerをうまく使えば、
ブラウザの共有ボタンからコンカレに飛ばすことが可能かも？（本当はこっちがやりたい）

TwitterのWeb Intent
[Web Intent | Docs | Twitter Developer Platform](https://developer.x.com/en/docs/x-for-websites/tweet-button/guides/web-intent)

## Why (Optional)
Webサイトなど、共有したい物があるときにURLをコピペするのが面倒・・・
→Web Intentがあればコピペせずに共有できる！（かも？）

**Comment by totegamma** [comment]
ブラウザの共有ボタンからコンカレに飛ばすやつはweb share target apiかな
それはそれとしてintentリンクはほしい！ urlはどうしようかな......

**Comment by totegamma** [comment]
https://caniuse.com/mdn-html_manifest_share_target
chrome for androidはいけそうだがsafari on iosは対応してないな...

**Comment by totegamma** [comment]
`/intent?title=&text=&url=` でつくってみました
ついでにweb share target APIをマニフェストに指定 (dcfebac42276f0c6b2d3d71b8498f112efd56ce0)してみたけれどもandroidだとシェア対象に出てきたりするのかしら 🤔

**Comment by ryotn** [comment]
実装ありがとうございます！
Web Intentの方は問題なさそうなんですけど、web share target APIの方は出てこないですね・・・。

**Comment by totegamma** [comment]
えーんなんでじゃろ
一応pwaのマニフェスト周りの更新が反映されるタイミングが謎(数回開き直した後？)というのもあるので時間をおいてまたみていただけると助かります...!!!

**Comment by totegamma** [comment]
windows上で、GoogleChromeだと再インストールしても一覧に出てこないけど、edgeだとインストールしたら一覧に出てくるようになった 🤔 

![image](https://github.com/user-attachments/assets/2f52a2c8-1a0c-4072-9b49-bead92da29b6)

まーtargetの方に関しては各ブラウザでの実装待ち[いつまで？]みたいなところもあるので、一旦完了ということでクローズ
